linters:
  enable:
    - bidichk
    - canonicalheader
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - fatcontext
    - gocritic
    - govet
    - inamedparam
    - ineffassign
    - intrange
    - misspell
    - nonamedreturns
    - prealloc
    - revive
    - sloglint
    - spancheck
    - staticcheck
    - unused
    - whitespace
    - wrapcheck
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: should pass the context parameter
    paths:
      - ./generated/generated.go
      - ./generated/models_gen.go
      - ./generated/
      - third_party$
      - builtin$
      - examples$
