name: release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: sh

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          #node-version-file: 'frontend/.nvmrc'

      #- name: Clear corepack cache
      #  run: corepack cache clean

      #- name: Remove corepack cache directory
      #  run: rm -rf ~/.cache/corepack

      - name: Enable corepack
        run: corepack enable

      - name: Build wasm
        run: go build -ldflags="-s -w" -v -o frontend/static/calculator.wasm ./wasm
        env:
          GOOS: js
          GOARCH: wasm

      #- name: Prepare pnpm with corepack
      #  run: corepack prepare pnpm@10.11.0 --activate

      - name: Build frontend
        working-directory: frontend
        run: |
          #pnpm --recursive update --latest
          pnpm install
          pnpm run build
          ls -lah build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
          exclude_assets: ''
